# Generated by Django 4.2.7 on 2025-03-10 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="sightseeings",
        ),
    ]
