# Generated by Django 4.2.7 on 2025-03-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_remove_plan_sightseeings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SightseeingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.plan"
                    ),
                ),
                (
                    "sightseeing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.sightseeing",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("sightseeing", "plan")},
            },
        ),
    ]
