# Generated by Django 4.2.7 on 2025-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_sightseeing_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sightseeing",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
